[project]
name = "acbrightspace"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pyotp>=2.9.0",
    "selenium>=4.39.0",
]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]
